# Generated by Django 5.0.1 on 2025-12-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("dislike", "Dislike"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                ],
                max_length=20,
            ),
        ),
    ]
